Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Tags/TagAnnotaionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using AutoMapper;

using My.Blog.Data.Models;
using My.Blog.Web.Infrastructure.Mapping;
using My.Blog.Web.Models.Posts;

namespace My.Blog.Web.Models.Tags
{
    public class TagAnnotaionViewModel : IMapFrom<Tag>, IHaveCustomMappings
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public bool IsDeleted { get; set; }

        public ICollection<PostAnnotationViewModel> Posts { get; set; }

        public DateTime? DeletedOn { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Tag, TagAnnotaionViewModel>()
                         .ForMember(model => model.Posts, opt => opt.Ignore());
        }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Tags/TagPaginationModel.cs
using System.Collections.Generic;

namespace My.Blog.Web.Models.Tags
{
    public class TagPaginationModel
    {
        public ICollection<TagAnnotaionViewModel> Model { get; set; }

        public int AllPages { get; set; }

        public int CurrentPage { get; set; }

        public int PageSize { get; set; }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Tags/TagsViewModel.cs
using System.Collections.Generic;

namespace My.Blog.Web.Models.Tags
{
    public class TagsViewModel
    {
        public IList<TagAnnotaionViewModel> Tags { get; set; }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

using My.Blog.Data.Models;
using My.Blog.Services.Contracts;
using My.Blog.Web.Models.Tags;
using My.Blog.Web.Common;
using My.Blog.Web.Helpers.Contracts;
using System.Linq;

namespace My.Blog.Web.Areas.Administration.Controllers
{
    public class TagsController : AdminController
    {
        private ITagService tagService;
        private IPaginator paginator;

        public TagsController(ITagService tagService, IMappingService mappingService, IPaginator paginator)
            : base(mappingService)
        {
            this.tagService = tagService ?? throw new ArgumentNullException();
            this.paginator = paginator ?? throw new ArgumentNullException();
        }

        public ActionResult All(int id = GlobalConstraints.AdminTagsPaginationStartPage, int pageSize = GlobalConstraints.AdminTagsPaginationPageSize)
        {
            var tags = tagService.GetAllAndDeleted().ToList();   
            var tagsModel = mappingService.Map<IList<Tag>, ICollection<TagAnnotaionViewModel>>(tags);

            var tagsViewModel = paginator.ApplyPagination<TagPaginationModel, TagAnnotaionViewModel>(id, pageSize, tagsModel);

            return this.View(tagsViewModel);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id, Name, IsActive")]TagAnnotaionViewModel tag)
        {
            if (ModelState.IsValid)
            {
                var entity = this.mappingService.Map<Tag>(tag);

                this.tagService.Add(entity);

                return this.RedirectToAction("All");
            }

            return this.View();
        }

        public ActionResult Edit(int id)
        {
            var tag = tagService.GetById(id);
            var tagViewModel = this.mappingService.Map<TagAnnotaionViewModel>(tag);

            return this.View(tagViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Name, IsActive")]TagAnnotaionViewModel tag)
        {
            if (ModelState.IsValid)
            {
                var entity = this.mappingService.Map<Tag>(tag);

                this.tagService.Update(entity);

                return this.RedirectToAction("All");
            }

            return this.View();
        }

        public ActionResult Delete(int id)
        {
            this.tagService.Delete(id);

            return this.RedirectToAction("All");
        }

        public ActionResult Recover(int id)
        {
            this.tagService.Recover(id);

            return this.RedirectToAction("All");
        }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using My.Blog.Data.Models;
using My.Blog.Services.Contracts;
using My.Blog.Web.Common;
using My.Blog.Web.Helpers.Contracts;
using My.Blog.Web.Models.Home;
using My.Blog.Web.Models.Posts;

namespace My.Blog.Web.Controllers
{

    public class TagsController : BaseController
    {
        private readonly ITagService tagService;
        private readonly IPaginator paginator;

        public TagsController(ITagService tagService, IMappingService mappingService, IPaginator paginator)
            : base(mappingService)
        {
            this.tagService = tagService ?? throw new ArgumentNullException();
            this.paginator = paginator ?? throw new ArgumentNullException();
        }

        public ActionResult ByTag(int id, int pageId = GlobalConstraints.HomePaginationStartPage, int pageSize = GlobalConstraints.HomePaginationPageSize)
        {
            var posts = this.tagService.GetById(id)
                .Posts
                .ToList();

            var postsModel = mappingService.Map<IList<Post>, ICollection<PostAnnotationViewModel>>(posts);

            var postsViewModel = paginator.ApplyPagination<HomePaginationModel, PostAnnotationViewModel>(pageId, pageSize, postsModel);

            this.ViewData["TagId"] = id;

            return this.View(postsViewModel);
        }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Views/Tags/All.cshtml
@model My.Blog.Web.Models.Tags.TagPaginationModel

@{
    ViewBag.Title = Resources.GlobalResources.Tags;
}

<h1>@Resources.GlobalResources.Tags</h1>

@if (!Model.Model.Any())
{
    <p>No tags</p>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>@Resources.GlobalResources.Id</th>
                <th>@Resources.GlobalResources.Name</th>
                <th>@Resources.GlobalResources.IsDeleted</th>
                <th>@Resources.GlobalResources.Tag</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>
                        @if (item.IsDeleted)
                        {
                            @Html.ActionLink(@Resources.GlobalResources.Recover, "Recover", "Tags", new { id = item.Id }, null)
                        }
                        else
                        {
                            @Html.ActionLink(@Resources.GlobalResources.Delete, "Delete", "Tags", new { id = item.Id }, null)
                        }
                    </td>
                    <td>@Html.ActionLink(Resources.GlobalResources.Edit, "Edit", "Tags", new { id = item.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>

    @Html.ActionLink(Resources.GlobalResources.Add, "Create", "Tags", new { Area = "Administration" }, htmlAttributes: new { @class = "btn btn-primary" })

    <div class="btn-group">
        @{
            if (Model.CurrentPage <= 1)
            {
                <span class="btn btn-primary" disabled="disabled"><<</span>
                <span class="btn btn-primary" disabled="disabled"><</span>
            }
            else
            {
                @Html.ActionLink("<<", "All", new { id = 1 }, new { @class = "btn btn-primary" })
                @Html.ActionLink("<", "All", new { id = Model.CurrentPage - 1 }, new { @class = "btn btn-primary" })
            }
        }

        @{
            int startPage = 1;
            int endPage = Model.AllPages;

            if (Model.AllPages > 10)
            {
                if (Model.CurrentPage > 5)
                {
                    startPage = Model.CurrentPage - 5;
                }

                if (Model.CurrentPage + 5 < Model.AllPages)
                {
                    endPage = Model.CurrentPage + 5;
                }
            }
        }

        @{
            if (Model.CurrentPage - 5 > 1)
            {
                <span class="btn btn-primary" disabled="disabled">...</span>
            }
        }

        @for (int pageIndex = startPage; pageIndex <= endPage; pageIndex++)
        {
            if (pageIndex != Model.CurrentPage)
            {
                @Html.ActionLink(pageIndex.ToString(), "All", new { controller = "tags", area = "Administration", id = pageIndex }, new { @class = "btn btn-primary" })
            }
            else
            {
                <span class="btn btn-primary" disabled="disabled">@pageIndex</span>
            }
        }

        @{
            if (Model.CurrentPage + 5 < Model.AllPages)
            {
                <span class="btn btn-primary" disabled="disabled">...</span>
            }
        }

        @{
            if (Model.CurrentPage >= Model.AllPages)
            {
                <span class="btn btn-primary" disabled="disabled">></span>
                <span class="btn btn-primary" disabled="disabled">>></span>
            }
            else
            {
                @Html.ActionLink(">", "All", new { id = Model.CurrentPage + 1 }, new { @class = "btn btn-primary" })
                @Html.ActionLink(">>", "All", new { id = Model.AllPages }, new { @class = "btn btn-primary" })
            }
        }
    </div>
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Views/Tags/Create.cshtml
@using My.Blog.Web.Models.Tags
@model TagAnnotaionViewModel

@{
    ViewBag.Title = Resources.GlobalResources.CreateTag;
}

@using (Html.BeginForm("Create", "Tags", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-12">

            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">

            <input type="submit" class="btn btn-default" value="Add" />
        </div>
    </div>
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Views/Tags/Edit.cshtml
@using My.Blog.Web.Models.Tags
@model TagAnnotaionViewModel

@{
    ViewBag.Title = Resources.GlobalResources.EditTags;
}

<h2>@Resources.GlobalResources.EditTag</h2>

@using (Html.BeginForm("Edit", "Tags", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.HiddenFor(m => m.Id)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-12">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-12">
            <input type="submit" class="btn btn-default" value=@Resources.GlobalResources.Edit />
        </div>
    </div>
}