Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Posts/CreatePostViewModel.cs
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

using My.Blog.Web.Models.Tags;
using My.Blog.Web.Common.Validators;

namespace My.Blog.Web.Models.Posts
{
    public class CreatePostViewModel
    {
        [Required]
        [Display(Name = "Title")]
        public string PostTitle { get; set; }

        [Required]
        [Display(Name = "Content")]
        public string PostContent { get; set; }

        public IList<TagAnnotaionViewModel> Tags { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [FileSize(250240)]
        [FileTypes("jpg, jpeg, png")]
        public HttpPostedFileBase File { get; set; }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Posts/PostAnnotationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using AutoMapper;

using My.Blog.Data.Models;
using My.Blog.Web.Helpers;
using My.Blog.Web.Infrastructure.Mapping;
using My.Blog.Web.Models.Tags;

namespace My.Blog.Web.Models.Posts
{
    public class PostAnnotationViewModel : IMapFrom<Post>, IHaveCustomMappings
    {
        private BlogUrlGenerator blogUrlGenerator;

        public PostAnnotationViewModel()
            : this(new BlogUrlGenerator())
        {

        }

        public PostAnnotationViewModel(BlogUrlGenerator blogUrlGenerator)
        {
            this.blogUrlGenerator = blogUrlGenerator;
        }

        public int Id { get; set; }

        [Required]
        [MinLength(5)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime CreatedOn { get; set; }

        public bool IsDeleted { get; set; }

        public DateTime? DeletedOn { get; set; }

        public string UserName { get; set; }

        public ICollection<TagAnnotaionViewModel> Tags { get; set; }

        public string Url
        {
            get
            {
                return blogUrlGenerator.GenerateUrl(this.Id, this.Title);
            }
        }

        public string PostImageName { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Post, PostAnnotationViewModel>().MaxDepth(0)
                .ForMember(model => model.UserName, opt => opt.MapFrom(data => data.User.UserName));
        }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Posts/PostPaginationModel.cs
using System.Collections.Generic;

namespace My.Blog.Web.Models.Posts
{
    public class PostPaginationModel
    {
        public ICollection<PostAnnotationViewModel> Model { get; set; }

        public int AllPages { get; set; }

        public int CurrentPage { get; set; }

        public int PageSize { get; set; }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Models/Posts/PostViewModel.cs
using System.Collections.Generic;

namespace My.Blog.Web.Models.Posts
{
    public class PostViewModel
    {
        public ICollection<PostAnnotationViewModel> Posts { get; set; }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using System.Linq;

using My.Blog.Data.Models;
using My.Blog.Services.Contracts;
using My.Blog.Web.Models.Posts;
using My.Blog.Web.Helpers.Contracts;
using My.Blog.Web.Models.Tags;
using My.Blog.Web.Common;

namespace My.Blog.Web.Areas.Administration.Controllers
{
    public class PostsController : AdminController
    {
        private readonly IPostService postService;
        private readonly ITagService tagService;
        private readonly IPaginator paginator;

        public PostsController(ITagService tagService, IPostService postService, IPaginator paginator,
             IMappingService mappingService)
            : base(mappingService)
        {
            this.postService = postService ?? throw new ArgumentNullException();
            this.tagService = tagService ?? throw new ArgumentNullException();
            this.paginator = paginator ?? throw new ArgumentNullException();
        }

        public ActionResult All(int id = GlobalConstraints.AdminPostsPaginationStartPage, int pageSize = GlobalConstraints.AdminPostsPaginationPageSize)
        {
            var posts = this.postService.GetAllAndDeleted().OrderByDescending(x => x.CreatedOn).ToList();
            var postsModel = mappingService.Map<IList<Post>, ICollection<PostAnnotationViewModel>>(posts);

            var postsViewModel = paginator.ApplyPagination<PostPaginationModel, PostAnnotationViewModel>(id, pageSize, postsModel);

            return this.View(postsViewModel);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostTitle, PostContent, Tags, File")] CreatePostViewModel model)
        {
            if (ModelState.IsValid)
            {

                if (model.File != null)
                {
                    string _fileName = Path.GetFileName(model.File.FileName);
                    string _path = Path.Combine(Server.MapPath(GlobalConstraints.PostImageFolderPath), _fileName);
                    model.File.SaveAs(_path);

                    var tags = model.Tags.Where(m => m.IsDeleted == true).ToList();

                    var tagsModel = mappingService.Map<ICollection<TagAnnotaionViewModel>, IList<Tag>>(tags);

                    this.postService.AddNew(tagsModel, model.PostTitle, model.PostContent, _fileName);

                    return this.RedirectToAction("All");
                }

                return this.RedirectToAction("Index");
            }

            return this.View();
        }

        public ActionResult Edit(int id)
        {
            var post = this.postService.GetById(id);
            var postViewModel = mappingService.Map<PostAnnotationViewModel>(post);

            return this.View(postViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Title, Content, CreatedOn, IsDeleted, DeletedOn, PostImageName")]PostAnnotationViewModel post)
        {
            if (ModelState.IsValid)
            {
                var entity = this.mappingService.Map<PostAnnotationViewModel, Post>(post);

                this.postService.Update(entity);

                return this.RedirectToAction("All", "Posts", null);
            }

            return this.View();
        }

        [ChildActionOnly]
        public ActionResult AddTags()
        {
            var tags = this.tagService.GetAll();
            var tagsModel = this.mappingService.Map<IEnumerable<Tag>, IList<TagAnnotaionViewModel>>(tags);

            var tagsViewModel = new TagsViewModel()
            {
                Tags = tagsModel
            };

            return this.PartialView("_AddTags", tagsViewModel);
        }

        public ActionResult Delete(int id)
        {
            this.postService.Delete(id);

            return this.RedirectToAction("All");
        }

        public ActionResult Recover(int id)
        {
            this.postService.Recover(id);

            return this.RedirectToAction("All");
        }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using My.Blog.Data.Models;
using My.Blog.Services.Contracts;
using My.Blog.Web.Models.Comments;

namespace My.Blog.Web.Controllers
{
    public class CommentsController : BaseController
    {
        private readonly IPostCommentService postCommentService;
        private readonly IPostService postService;

        public CommentsController(IPostCommentService postCommentService, IPostService postService, IMappingService mappingService)
            : base(mappingService)
        {
            this.postCommentService = postCommentService ?? throw new ArgumentNullException();
            this.postService = postService ?? throw new ArgumentNullException();
        }

        public ActionResult All(int id)
        {
            this.Request.IsAjaxRequest();

            var comments = this.postCommentService
                .GetAll()
                .Where(c => c.PostId == id)
                .ToList();

            var postCommentsModel = mappingService.Map<IList<PostComment>, ICollection<PostCommentAnnotationViewModel>>(comments);

            var postCommentViewModel = new PostCommentViewModel()
            {
                Comments = postCommentsModel
            };

            return this.PartialView(postCommentViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNew([Bind(Include = "Content")]PostCommentAnnotationViewModel comment, int PostId)
        {
            if (ModelState.IsValid)
            {
                this.postCommentService.AddNew(comment.Content, PostId);

                return this.RedirectToAction("Index", "Home", null);
            }

            return this.View();
        }
    }
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Views/Posts/All.cshtml
@model My.Blog.Web.Models.Posts.PostPaginationModel

@{
    ViewBag.Title = Resources.GlobalResources.Posts;
}

<h1>@Resources.GlobalResources.Posts</h1>

@if (!Model.Model.Any())
{
    <p>No posts yet!</p>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>@Resources.GlobalResources.Id</th>
                <th>@Resources.GlobalResources.Name</th>
                <th>@Resources.GlobalResources.CreatedOn</th>
                <th>@Resources.GlobalResources.IsDeleted</th>
                <th>@Resources.GlobalResources.Post</th>
                <th>@Resources.GlobalResources.Comments</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td><a href="@item.Url">@item.Title</a></td>
                    <td>@item.CreatedOn</td>
                    <td>
                        @if (item.IsDeleted)
                        {
                            @Html.ActionLink(@Resources.GlobalResources.Recover, "Recover", "Posts", new { id = item.Id }, null)
                        }
                        else
                        {
                            @Html.ActionLink(@Resources.GlobalResources.Delete, "Delete", "Posts", new { id = item.Id }, null)
                        }
                    </td>
                    <td>
                        @Html.ActionLink(@Resources.GlobalResources.Edit, "Edit", "Posts", new { id = item.Id }, null)
                    </td>
                    <td>
                        @Html.ActionLink(@Resources.GlobalResources.Edit, "AllByPostId", "Comments", new { id = item.Id }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>


    <div class="btn-group">
        @{
            if (Model.CurrentPage <= 1)
            {
                <span class="btn btn-primary" disabled="disabled"><<</span>
                <span class="btn btn-primary" disabled="disabled"><</span>
            }
            else
            {
                @Html.ActionLink("<<", "All", new { id = 1 }, new { @class = "btn btn-primary" })
                @Html.ActionLink("<", "All", new { id = Model.CurrentPage - 1 }, new { @class = "btn btn-primary" })
            }
        }

        @{
            int startPage = 1;
            int endPage = Model.AllPages;

            if (Model.AllPages > 10)
            {
                if (Model.CurrentPage > 5)
                {
                    startPage = Model.CurrentPage - 5;
                }

                if (Model.CurrentPage + 5 < Model.AllPages)
                {
                    endPage = Model.CurrentPage + 5;
                }
            }
        }

        @{
            if (Model.CurrentPage - 5 > 1)
            {
                <span class="btn btn-primary" disabled="disabled">...</span>
            }
        }

        @for (int pageIndex = startPage; pageIndex <= endPage; pageIndex++)
        {
            if (pageIndex != Model.CurrentPage)
            {
                @Html.ActionLink(pageIndex.ToString(), "All", new { controller = "posts", area = "Administration", id = pageIndex }, new { @class = "btn btn-primary" })
            }
            else
            {
                <span class="btn btn-primary" disabled="disabled">@pageIndex</span>
            }
        }

        @{
            if (Model.CurrentPage + 5 < Model.AllPages)
            {
                <span class="btn btn-primary" disabled="disabled">...</span>
            }
        }

        @{
            if (Model.CurrentPage >= Model.AllPages)
            {
                <span class="btn btn-primary" disabled="disabled">></span>
                <span class="btn btn-primary" disabled="disabled">>></span>
            }
            else
            {
                @Html.ActionLink(">", "All", new { id = Model.CurrentPage + 1 }, new { @class = "btn btn-primary" })
                @Html.ActionLink(">>", "All", new { id = Model.AllPages }, new { @class = "btn btn-primary" })
            }
        }
    </div>
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Views/Posts/Create.cshtml
@using My.Blog.Web.Models.Posts
@model CreatePostViewModel

@{
    ViewBag.Title = Resources.GlobalResources.CreatePost;
}

<script src="@Url.Content("~/Scripts/tinymce/tinymce.min.js")" type="text/javascript"></script>

<script type="text/javascript">
    tinyMCE.init({
        selector: "#PostContent",
    });
</script>

@using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <h4>@Resources.GlobalResources.CreatePost</h4>
    <div class="form-group">
        @Html.LabelFor(m => m.PostTitle, new { @class = "col-md-2 control-label" })
        <div class="col-md-12">
            @Html.TextBoxFor(m => m.PostTitle, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
            @Html.ValidationMessageFor(m => m.PostTitle, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PostContent, new { @class = "col-md-2 control-label" })
        <div class="col-md-12">
            @Html.TextAreaFor(m => m.PostContent, 10, 10, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
            @Html.ValidationMessageFor(m => m.PostContent, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            @Html.TextBox("file", "", new { type = "file", @class = "form-control", style = "width: 100%; max-width: 100%;" })
            @Html.ValidationMessage("file", "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-12">
        @Html.Action("AddTags", "Posts")
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" class="btn btn-default" value=@Resources.GlobalResources.AddPost />
        </div>
    </div>
}

Programming with C#/Workshops/My.Blog/My.Blog.Web/Areas/Administration/Views/Posts/Edit.cshtml
@model My.Blog.Web.Models.Posts.PostAnnotationViewModel

@{
    ViewBag.Title = Resources.GlobalResources.EditPost;
}

<script src="@Url.Content("~/Scripts/tinymce/tinymce.min.js")" type="text/javascript"></script>

<script type="text/javascript">
    tinyMCE.init({
        selector: "#PostContent",
    });
</script>

<h2>@Resources.GlobalResources.EditPost</h2>

@using (Html.BeginForm("Edit", "Posts", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.HiddenFor(m => m.Id)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-12">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
            @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Content, new { @class = "col-md-2 control-label" })
        <div class="col-12">
            @Html.TextAreaFor(m => m.Content, 10, 10, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
            @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.CreatedOn, new { @class = "col-md-2 control-label" })
        <div class="col-12">
            @Html.TextBoxFor(m => m.CreatedOn, new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IsDeleted, new { @class = "col-md-2 control-label" })
        <div class="col-12">
            @Html.DropDownListFor(m => m.IsDeleted, new SelectList(new List<string>() { "true", "false" }))
        </div>
    </div>
    <div class="form-group">
        @Html.HiddenFor(m => m.DeletedOn)
    </div>
    <div class="form-group">
        @Html.HiddenFor(m => m.PostImageName)
    </div>
    <div class="form-group">
        <div class="col-12">
            <input type="submit" class="btn btn-default" value=@Resources.GlobalResources.Edit />
        </div>
    </div>
}